Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

LoginGUI.Title= Saioa hasi
LoginGUI.Email= Email
LoginGUI.Username= Erabiltzailea
LoginGUI.Password= Pasahitza
LoginGUI.LoginButton= Saioa hasi
LoginGUI.CloseButton= Itxi
LoginGUI.error= Ez dira aurkitu erabiltzailerik email edo pasahitza honekin 

RegisterGUI.Title= Erregistratu
RegisterGUI.Email= Email-a
RegisterGUI.Username= Erabiltzailea 
RegisterGUI.Password= Pasahitza
RegisterGUI.RepeatPassword= Errepikatu pasahitza
RegisterGUI.RegisterButton= Erregistratu
RegisterGUI.CloseButton= Itxi
RegisterGUI.notValidMail= Baliozkoa den email bat idatzi
RegisterGUI.notValidPassword= Pasahitzak 5 karktere, letra larria eta xehea eta zenbaki bat izan behar du.
RegisterGUI.PasswordMismatch= Pasahitzak berdinak izan behar dira
RegisterGUI.UserAlreadyExists = Email hau jada erabilia izan da
RegisterGUI.UsernameEmpty = Sartu ezazu erabiltzaile izen bat

MainGUI.Login= Saioa hasi
MainGUI.Register= Erregistratu
MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.ShowProfile=Profila ikusi
MainGUI.MainTitle=Merkatua

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.NoOnSale=Ez dituzu produktuak eskaintzan
QuerySalesGUI.NoPurchased=Ez dituzu produkturik erosi
QuerySalesGUI.NoWhishList=Ez dituzu produkturik WhisList-ean
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.buyButton=Erosi
ShowSaleGUI.addToWishListButton=Gustukoetara gehitu
ShowSaleGUI.NotEnoughMoney=Ez duzu diru nahikoa

ShowProfileGUI.name=Erabiltzailea
ShowProfileGUI.mail=Email
ShowProfileGUI.balance=Saldoa
ShowProfileGUI.sWishList=WishList-a erakutsi 
ShowProfileGUI.sBoughts=Erosketak erakutsi
ShowProfileGUI.sMovements=Mugimenduak erakutsi
ShowProfileGUI.mBalance=Saldoa kudeatu
ShowProfileGUI.title=Zure profila
ShowProfileGUI.close=Itxi
ShowProfileGUI.onSale=Zure produktuak erakutsi

ManageMoneyGUI.title=Dirua kudeatu
ManageMoneyGUI.amount=Kopurua
ManageMoneyGUI.password=Pasahitza
ManageMoneyGUI.withdraw=Atera
ManageMoneyGUI.deposit=Sartu
ManageMoneyGUI.confirm=Konfirmatu
ManageMoneyGUI.close=Itxi
ManageMoneyGUI.NotSelected=Aukeretako bat sakatu
ManageMoneyGUI.IncorrectPassword=Pasahitza okerra
ManageMoneyGUI.AmountError=Errorea kopuruan
ManageMoneyGUI.NotEnoughMoney=Ez duzu diru nahikoa

DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da